lint

diff --git a/.github/workflows/analyze-modified-files.yml b/.github/workflows/analyze-modified-files.yml
--- a/.github/workflows/analyze-modified-files.yml
+++ b/.github/workflows/analyze-modified-files.yml
@@ -14,29 +14,29 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - uses: actions/setup-python@v4
-        with:
-          python-version: 3.8
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip flake8 mypy
-          python ModuleUpdate.py --append "WebHostLib/requirements.txt" --force --yes
-
-      - name: Determine modified files
-      - run: |
-          git fetch origin $BASE_SHA $HEAD_SHA
-          DIFF=$(git diff --diff-filter=d --name-only $BASE_SHA...$HEAD_SHA -- "*.py")
-          echo "diff=$DIFF" >> $GITHUB_ENV
-          echo modified files:
-          echo $DIFF
-
-      - name: Lint modified files with flake8
-        if: env.diff != ""
-        run: |
-          flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}
-
-      - name: Type check modified files with mypy
-        if: env.diff != "" && (success() || failure())
-        run: |
-          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
+#      - uses: actions/setup-python@v4
+#        with:
+#          python-version: 3.8
+#
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip flake8 mypy
+#          python ModuleUpdate.py --append "WebHostLib/requirements.txt" --force --yes
+#
+#      - name: Determine modified files
+#      - run: |
+#          git fetch origin $BASE_SHA $HEAD_SHA
+#          DIFF=$(git diff --diff-filter=d --name-only $BASE_SHA...$HEAD_SHA -- "*.py")
+#          echo "diff=$DIFF" >> $GITHUB_ENV
+#          echo modified files:
+#          echo $DIFF
+#
+#      - name: Lint modified files with flake8
+#        if: env.diff != ""
+#        run: |
+#          flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}
+#
+#      - name: Type check modified files with mypy
+#        if: env.diff != "" && (success() || failure())
+#        run: |
+#          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
