lint

diff --git a/.github/workflows/analyze-modified-files.yml b/.github/workflows/analyze-modified-files.yml
--- a/.github/workflows/analyze-modified-files.yml
+++ b/.github/workflows/analyze-modified-files.yml
@@ -34,12 +34,12 @@ jobs:
           echo $DIFF
           echo "diff=$DIFF" >> $GITHUB_ENV
 
-      - name: Lint modified files with flake8
-        if: env.diff != ""
-        run: |
-          flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}
-
-      - name: Type check modified files with mypy
-        if: env.diff != "" && (success() || failure())
-        run: |
-          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
+#      - name: Lint modified files with flake8
+#        if: env.diff != ""
+#        run: |
+#          flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}
+#
+#      - name: Type check modified files with mypy
+#        if: env.diff != "" && (success() || failure())
+#        run: |
+#          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
