lint

diff --git a/.github/workflows/analyze-modified-files.yml b/.github/workflows/analyze-modified-files.yml
--- a/.github/workflows/analyze-modified-files.yml
+++ b/.github/workflows/analyze-modified-files.yml
@@ -42,7 +42,7 @@ jobs:
         run: |
           flake8 --count --max-complexity=10 --max-doc-length=120 --max-line-length=120 --statistics ${{ env.diff }}
 
-      - name: Type check modified files with mypy
-        if: env.diff != "" && (success() || failure())
-        run: |
-          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
+#      - name: Type check modified files with mypy
+#        if: env.diff != "" && (success() || failure())
+#        run: |
+#          mypy --follow-imports=silent --install-types --non-interactive --strict ${{ env.diff }}
